### ISSUE TITLE
Pipe.Net for Mac and Linux

### ISSUE THREAD

**Issue by Anji494** [grahammcallister/Pipe.Net#1]
Hi,

Thanks for the Pipe.net , it works pretty well for windows, but when i try to run Node.Demo it in the mac or linux its not working. Does named pipes work in mac and linux, if yes please let me know how??

**Comment by grahammcallister** [comment]
Hi,

This first version was written on .Net Framework so is not cross platform. Conceptually I think it can work on other platforms but I hadn't planned on looking at that. You're welcome to give it a try. What specific error do you get?

**Comment by Anji494** [comment]
Hi Grahamm,

Thanks for the response, i have used your code on a .NetCore application, so as you said it should technically work on mac and linux. But when i try to run the Node.Demo on mac i got the following error.

```
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: connect ENOENT \.\pipe\Pipe.Server
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
```
I suspect this more of issue in javascript library,but not sure as i have little knowledge on it.

**Comment by grahammcallister** [comment]
Thanks for pasting the error here @Anji494. I tried running the demo on a Mac and I get the same error you did. After doing some research, it looks like it will be possible to get the library running on .Net Core since the System.IO.Pipes API is supported (see https://github.com/dotnet/corefx/blob/master/src/System.IO.Pipes) I have decided to try port the library to .Net Core and will keep you updated on the progress here.

**Comment by grahammcallister** [comment]
Busy with the port, I am trying to fix an exception when I open the pipe on Mac OS: System.PlatformNotSupportedException: Message transmission mode is not supported on this platform.
